ALTER TABLE Users
    DROP CONSTRAINT PK__Users__77222459C3E0D7D2;

ALTER TABLE Users
    ADD PRIMARY KEY (Id);

ALTER TABLE Users
    ADD UNIQUE (Username);

ALTER TABLE Users
    ADD CHECK (DATALENGTH(Username) >= 3);